# This is a basic workflow to help you get started with Actions

name: My-first-pipeline
env :
  PACKAGE_NAME: "deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps: 
    - name: Print message in testing
      run: echo Hello, world!

    - name: Execure few commands
      run: |
        echo message_1
        echo message_2   
        echo Package name is ${{ env.PACKAGE_NAME }}     
  
  deploy:
    runs-on: ubuntu-latest
    needs  : [testing]

    steps:
    - name: Print message in deploy
      run: echo Hello, worldddddddddddddddddddddd!

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List current folder
      run: ls -la

    - name: packages nano
      run: nano --version  
