# This is a basic workflow to help you get started with Actions

name: My-first-pipeline

on: 
  push:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps: 
    - name: Run a one-line script
      run: echo Hello, world!
     
